### ISSUE TITLE
APCu not supported?

### ISSUE THREAD

**Issue by andig** [KKoPV/PVLng#38]
With php 5.6/ apcu installed, the cache interface seems to have changed and the APC class needs the following fixes:

    public function getHits() {
        $stats = apc_cache_info();
        return $stats['nhits'];
        // return $stats['num_hits'];
    }

    public function getMisses() {
        $stats = apc_cache_info();
        return $stats['nmisses'];
        // return $stats['num_misses'];
    }

Would it make sense to use something standard instead, e.g. Doctrine\Cache?

**Comment by K-Ko** [comment]
Base of the caching is an very old own development...

From next major release 3.0.0 also composer will be used, afterwards I'll check usage of more common libraries.
